server:
  port: ${PORT:8081}

  error:
    include-message: always
    whitelabel:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: air-quality-svc

  config:
    import: optional:file:.env[.properties]

  threads:
    virtual:
      enabled: true

  data:
    mongodb:
      uri: ${APP_SERVICE_MONGO_URL:uri}
      database: ${APP_SERVICE_MONGO_DB:air-quality-db}

app:
  schedule:
    cron: ${APP_SERVICE_SCHEDULER_CRONE:*/15 * * * * *}

  rabbitmq:
    username: ${APP_SERVICE_RABBITMQ_USERNAME}
    password: ${APP_SERVICE_RABBITMQ_PASSWORD}
    port: ${APP_SERVICE_RABBITMQ_PORT:5672}
    host: ${APP_SERVICE_RABBITMQ_HOST:localhost}
    virtualhost: ${APP_SERVICE_RABBITMQ_VIRTUAL_HOST}
    queue: ${APP_SERVICE_RABBITMQ_QUEUE:air-quality-queue}